### ISSUE TITLE
Sample Docker Compose?

### ISSUE THREAD

**Issue by contagon** [vxav/esphome-avahi#1]
I've been pulling out my hair trying to get mDNS to play nicely with esphome - finally got mDNS working on my host machine via avahi, now working on getting it into the container.

Would you mind sharing a sample docker-compose file of how you're using this? Here's what I'm using currently:

```yaml
version: '3'
services:
  esphome:
    container_name: esphome
    image: vxav/esphome-avahi
    volumes:
      - $DATA/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
```

Strangely, I can't even ping my esphome devices via *.local using this, so I figured something might be up with my compose file. Thanks for your help!
